version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: github
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  fetcher:
    build: ./fetcher
    depends_on:
      - db
